# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  directory:  # id of input
    description: 'directory of python code'
    required: false
    default: '.'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}